Host: "www.devlead.se"
SiteTitle: "@devlead - Mattias Karlsson's Blog"
PostSources: "posts/**/*"
Image: "https://cdn.devlead.se/clipimg-vscode/2021/01/11/1f2af322-a19f-753d-bd3e-00118dc674f1.png?sv=2019-12-12&st=2021-01-10T15%3A16%3A48Z&se=2031-01-11T15%3A16%3A48Z&sr=b&sp=r&sig=RYHdZjTvO%2Fw0tUGsgnIiGJRhTiQQPHnEsSKtnV14Yoc%3D"
Copyright: => $"© Mattias Karlsson {DateTime.Now.Year}"
LinksUseHttps: true
EditLink: => "https://github.com/devlead/devlead.se/edit/main/src/DevLead/input/" + doc.Source.GetRelativeInputPath()